# Generated by Django 3.2.16 on 2022-10-19 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('PICK_UP_POINT', 'pick_up_point'), ('DROP_OFF_POINT', 'drop_off_point')], max_length=20)),
                ('driver_id', models.IntegerField()),
                ('vehicle_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('cargo_tonnage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
